---
title: "2021年5月17日 贝叶斯作业"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# lab10
```{r}
x=seq(-10,10,0.1)
norm_y=dnorm(x)
logi_y=exp(-x)/(1+exp(-x))^2
cauc_y=1/3.1415926/(1+x^2)
stud_y=dt(x,5)
norm1_y=dnorm(x,1,2)
```

```{r}
library(ggplot2)
library(data.table)
df=data.table(x=x,norm01=norm_y,logistic=logi_y,cauchy=cauc_y,
              student5=stud_y,norm12=norm1_y)
df=melt(df,id="x")
p=ggplot(df,aes(x=x,y=value,group=variable,color=variable))+
  geom_line()
p
```

从图像中可以看到，t分布最为接近目标分布，接下来依次为柯西分布、逻辑分布、正态分布N（1，2）

下面依次进行拒绝抽样

### t分布

```{r}
g=function(x){
  dt(x,5)
}
g_sample=function(n){
  rt(n,5)
}

f=function(x){
  dnorm(x)
}

h=function(x){
  g(x)/f(x)
}


reject_sample=function(n=1000){
  u=runif(n)
  g_sam=g_sample(n)
  m=1/optimize(h, c(-10, 10), tol = 0.000001)$objective
  temp=f(g_sam)/(m*g(g_sam))
  target_sample=g_sam[u<=temp]
  #print(head(temp))
  list(accept_rate=1/m,target_sample=target_sample,
       real_accept_rate=length(target_sample)/n,
       g_sample=g_sam,u=u)
}

temp=reject_sample(1000)
f_sample=density(temp$target_sample)

p=ggplot()+geom_line(aes(x=f_sample$x,y=f_sample$y),colour="red")+
  geom_line(aes(x=x,norm_y),alpha=0.8)
print(p)
cat("theoretical accept rate:",temp$accept_rate,'\n',
    'real accept rate:',temp$real_accept_rate,sep = '')
```

红色曲线是通过拒绝抽样得到的密度曲线，黑色的为理论密度曲线，可以看到两者相似程度较高，可以说拒绝抽样效果较好。

### 柯西分布

```{r}
g=function(x){
  dcauchy(x)
}
g_sample=function(n){
  rcauchy(n)
}
temp=reject_sample(1000)
f_sample=density(temp$target_sample)

p=ggplot()+geom_line(aes(x=f_sample$x,y=f_sample$y),colour="red")+
  geom_line(aes(x=x,norm_y),alpha=0.8)
print(p)
cat("theoretical accept rate:",temp$accept_rate,'\n',
    'real accept rate:',temp$real_accept_rate,sep = '')
```


### 逻辑分布

```{r}
g=function(x){
  dlogis(x)
}
g_sample=function(n){
  rlogis(n)
}
temp=reject_sample(1000)
f_sample=density(temp$target_sample)

p=ggplot()+geom_line(aes(x=f_sample$x,y=f_sample$y),colour="red")+
  geom_line(aes(x=x,norm_y),alpha=0.8)
print(p)
cat("theoretical accept rate:",temp$accept_rate,'\n',
    'real accept rate:',temp$real_accept_rate,sep = '')
```


```{r}
g=function(x){
  dnorm(x,1,2)
}
g_sample=function(n){
  rnorm(n,1,2)
}
temp=reject_sample(1000)
f_sample=density(temp$target_sample)

p=ggplot()+geom_line(aes(x=f_sample$x,y=f_sample$y),colour="red")+
  geom_line(aes(x=x,norm_y),alpha=0.8)
print(p)
cat("theoretical accept rate:",temp$accept_rate,'\n',
    'real accept rate:',temp$real_accept_rate,sep = '')
```

