---
title: "2021年5月13日 非参数作业"
author:
  - tassadar667
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
geometry: "left=2.5cm,right=2cm,top=3cm,bottom=2.5cm"
---

```{r setup, include=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1
```{r}
library(data.table)
ridit.test=function(x,group="sum"){
  m=ncol(x)
  n=nrow(x)
  row_sum=rowSums(x)
  col_sum=colSums(x)
  if(group=="sum"){
    temp0=col_sum
  }
  else{
    temp0=x[group,]
  }
  temp=temp0/2
  ac=c(0,cumsum(temp0)[1:(m-1)])
  temp1=temp+ac
  r=temp1/sum(temp0)
  p=data.table("case"=temp0,"case/2"=temp,"ac"=ac,"sum23"=temp1,"r"=r,"sum"=r*temp0)
  ri=c()
  for (i in 1:n) {
    ri=c(ri,sum(r*x[i,])/sum(x[i,]))
  }
  for (i in 1:n) {
    up=ri+1/sqrt(3*row_sum)
    low=ri-1/sqrt(3*row_sum)
  }
  ri_table=data.table("r"=ri,low,up)
  w=12*sum((ri-0.5)^2*row_sum)
  p_value=1-pchisq(w,n-1)
  ans=list("comput_r"=p,"Ri"=ri_table,"W"=w,"Pvalue"=p_value)
  
}
x1=c(90,23,53,21,13)
x2=c(47,34,28,18,5)
x3=c(20,13,10,5,2)
x4=c(28,32,33,45,16)
x5=c(34,28,52,40,10)
x=matrix(c(x1,x2,x3,x4,x5),nrow = 5,byrow =TRUE)
ans=ridit.test(x)

```

使用Ridit检验法

$H_0:$各项满意度没有差异

$H_1:$各项满意度之间存在差异

```{r}
print(ans$comput_r)
```
选择和为标准组，r的计算过程如上

```{r}
print(ans$Ri)
```
Ri计算如上

```{r}
print(ans$W)
print(ans$Pvalue)
```
W为43.81，P值几乎为0

P小于0.05，在显著性水平为0.05前提下，拒绝原假设，认为有差异。

# 2
```{r}
library(foreign)
camera=read.spss("camera-chisq2.sav")
attach(camera)
outlook_female=rbind(table(c01,d1=="male")[,1],
                     table(c02,d1=="male")[,1],
                     table(c03,d1=="male")[,1],
                     table(c04,d1=="male")[,1],
                     table(c05,d1=="male")[,1])
outlook_male=rbind(table(c01,d1=="male")[,2],
                   table(c02,d1=="male")[,2],
                   table(c03,d1=="male")[,2],
                   table(c04,d1=="male")[,2],
                   table(c05,d1=="male")[,2])
```


按照性别进行分类

```{r}
(female_ans=ridit.test(outlook_female))
(male_ans=ridit.test(outlook_male))
```

男女性都对外观的不同方面重视程度不同

```{r}
pplot=function(x,xlab="",ylab=""){
  plot(0,0,ylim=c(0,1),xlim=c(1,length(x$r)),xlab=xlab,ylab=ylab)
  abline(h=0.5)
  for (i in 1:length(x$r)) {
    lines(c(i,i),c(x$low[i],x$up[i]),lwd=2)
  }
}
```

绘图函数

```{r}
pplot(female_ans$Ri,xlab = "female_outlook")
pplot(male_ans$Ri,xlab = "male_outlook")
```

两者没有出现显著差别，大家都较为重视操作便利性和颜色多样性

```{r}
func_female=rbind(table(c11,d1=="male")[,1],
                  table(c12,d1=="male")[,1],
                  table(c13,d1=="male")[,1],
                  table(c14,d1=="male")[,1],
                  table(c15,d1=="male")[,1],
                  table(c16,d1=="male")[,1])
func_male=rbind(table(c11,d1=="male")[,2],
                table(c12,d1=="male")[,2],
                table(c13,d1=="male")[,2],
                table(c14,d1=="male")[,2],
                table(c15,d1=="male")[,2],
                table(c16,d1=="male")[,2])
```

```{r}
(female_ans=ridit.test(func_female))
(male_ans=ridit.test(func_male))
```

```{r}
pplot(female_ans$Ri,xlab = "female_function")
pplot(male_ans$Ri,xlab = "male_function")
```
两者没有出现显著差别，大家都较为重视操连拍和拍摄角度，对于是否可以上网不太重视

尝试从使用目的方面分类，分为业余和专业两方面
```{r}
amateur_use=rbind(table(c01,a02=="Personal or family use")[,2],
                  table(c02,a02=="Personal or family use")[,2],
                  table(c03,a02=="Personal or family use")[,2],
                  table(c04,a02=="Personal or family use")[,2],
                  table(c05,a02=="Personal or family use")[,2],
                  table(c11,a02=="Personal or family use")[,2],
                  table(c12,a02=="Personal or family use")[,2],
                  table(c13,a02=="Personal or family use")[,2],
                  table(c14,a02=="Personal or family use")[,2],
                  table(c15,a02=="Personal or family use")[,2],
                  table(c16,a02=="Personal or family use")[,2])
profession_use=rbind(table(c01,a02=="Personal or family use")[,1],
                     table(c02,a02=="Personal or family use")[,1],
                     table(c03,a02=="Personal or family use")[,1],
                     table(c04,a02=="Personal or family use")[,1],
                     table(c05,a02=="Personal or family use")[,1],
                     table(c11,a02=="Personal or family use")[,1],
                     table(c12,a02=="Personal or family use")[,1],
                     table(c13,a02=="Personal or family use")[,1],
                     table(c14,a02=="Personal or family use")[,1],
                     table(c15,a02=="Personal or family use")[,1],
                     table(c16,a02=="Personal or family use")[,1])
```

```{r}
(amateur_ans=ridit.test(amateur_use))
(profession_ans=ridit.test(profession_use))
```
```{r}
pplot(amateur_ans$Ri,xlab = "amateur")
pplot(profession_ans$Ri,xlab="profession")
```

两者没有出现显著差别，总的来说专业用途的人组件差距略小，造成原因可能是他们本身对相机功能参数较为了解，认为这些都是相机基本都有的功能。

总体上，人们较为在意操作的便利性，连拍性能，任意拍摄角度。
