---
title: "2021年4月15日 非参数作业"
author: "tassadar667"
date: "2021/4/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1
```{r}
bootstrap=function(x,p,alpha=0.05,num=1000){
  n=round(length(x)*0.7)
  p_seq=c()
  sd_seq=c()
  for (i in 1:num) {
    s=sample(x,n,replace = TRUE)
    p_seq=c(p_seq,quantile(s,p))
    sd_seq=c(sd_seq,sd(p_seq))
  }
  temp=mean(p_seq)
  temp1=sd(p_seq)*qnorm(1-alpha/2)
  return(list(sd=sd(p_seq),p_seq=p_seq,sd_seq=sd_seq,
              conf=c(temp-temp1,temp+temp1)))
}
sample_num=1000
x=rnorm(100,sd=5)
ans=bootstrap(x,0.25,num = sample_num)
plot(1:sample_num,ans$sd_seq)
print(ans$conf)
```

# 2
## 2.1
```{r}
x=rnorm(100,mean = 5)

canshu_boot=function(x,num=1000,alpha=0.05){
  s=sd(x)
  m=mean(x)
  theta_seq=c()
  sd_seq=c()
  for (i in 1:num) {
    temp=rnorm(100,mean = m,sd=s)
    theta=exp(mean(temp))
    theta_seq=c(theta_seq,theta)
    sd_seq=c(sd_seq,sd(theta_seq))
  }
  temp=2*mean(theta_seq)
  low=temp-quantile(theta_seq,1-alpha/2)
  up=temp-quantile(theta_seq,alpha/2)
  return(list(sd=sd(theta_seq),theta_seq=theta_seq,
              sd_seq=sd_seq,
              conf=c(low,up)))
}

feicanshu_boot=function(x,num=1000,alpha=0.05){
  theta_seq=c()
  sd_seq=c()
  for (i in 1:num) {
    temp=sample(x,round(length(x)*0.7),replace = TRUE)
    theta=exp(mean(temp))
    theta_seq=c(theta_seq,theta)
    sd_seq=c(sd_seq,sd(theta_seq))
  }
  temp=2*mean(theta_seq)
  low=temp-quantile(theta_seq,1-alpha/2)
  up=temp-quantile(theta_seq,alpha/2)
  return(list(sd=sd(theta_seq),theta_seq=theta_seq,
              sd_seq=sd_seq,
              conf=c(low,up)))
}

ans=canshu_boot(x)
ans_1=feicanshu_boot(x)

print(ans$conf)
print(ans$sd)
print(ans_1$conf,ans_1$sd)
print(ans_1$sd)
```
两者相差不多, 但是参数方法的信息更多，置信区间较小，方差较小


```{r}
hist(ans$theta_seq)
hist(ans_1$theta_seq)

```
两者的分布没有显著区别，整体为偏左的正态分布

# 3
```{r}
x=c(4.12,5.81,7.63,9.74,10.39,11.92,12.32,12.89,13.54,14.45)
r=rank(abs(x-8))
print(r)
s=c()
sgn=function(x){
  if(x>0){
    return(1)
  }
  else{
    return(-1)
  }
}
for (i in 1:length(x)) {
  s=c(s,pnorm((1+r[i])/(length(x))+1))*sgn(x[i]-8)
}
print(s)
t=sum(s)/sum(s^2)
p=(1-pnorm(t))*2
cat("t=",t,'\n',sep = '')
cat('p-value=',p,'\n',sep = '')
```

在显著性水平为0.05的前提下，不能否定原假设，即认为中位数为8